parameters:
  - name: validationRules
    type: object
    default:
      - sourceBranches:
          - 'refs/heads/task/task-*'
          - 'refs/heads/task-resolution/*'
        targetBranch: 'refs/heads/feature/feature-*'
      - sourceBranches:
          - 'refs/heads/team/team-*'
          - 'refs/heads/sprint/sprint-*'
          - 'refs/heads/task-resolution/*'
          - 'refs/heads/QA'
        targetBranch: 'refs/heads/develop'
      - sourceBranches:
          - 'refs/heads/develop'
          - 'refs/heads/task-resolution/*'
          - 'refs/heads/master'
        targetBranch: 'refs/heads/QA'
      - sourceBranches:
          - 'refs/heads/QA'
          - 'refs/heads/task-resolution/*'
        targetBranch: 'refs/heads/release/*'
      - sourceBranches:
          - 'refs/heads/task/task-*'
        targetBranch: 'refs/heads/hotfix/hotfix-*'
      - sourceBranches:
          - 'refs/heads/release/*'
          - 'refs/heads/task-resolution/*'
          - 'refs/heads/hotfix/hotfix-*'
        targetBranch: 'refs/heads/master'

stages:
- stage: PoliticasDoD
  displayName: "Políticas DoD"
  jobs:
  - job: PoliticasRamas
    displayName: "🛂 Politica de 🌵Ramas"
    pool:
      name: "Agents-AutoScaling"
    condition: |
      and(
        succeeded(),
        not(or(
          eq(variables['System.PullRequest.SourceRepositoryName'], 'properties'),
          eq(variables['System.PullRequest.SourceRepositoryName'], 'pipelines-projects')
        ))
      )
    steps:
      - bash: |
          echo "🛂 Politica de 🌵Ramas"

          source_branch="$(System.PullRequest.SourceBranch)"
          target_branch="$(System.PullRequest.TargetBranch)"

          PR_COLLECTION_URI="$(System.PullRequest.SourceRepositoryUri)"
          PR_TARGET_REPO_NAME="${PR_COLLECTION_URI##*/}"
          PR_ID="$(System.PullRequest.PullRequestId)"
          PR_LINK="$(System.PullRequest.SourceRepositoryUri)/pullrequest/${PR_ID}"

          if [[ "$PR_TARGET_REPO_NAME" = "properties" || "$PR_TARGET_REPO_NAME" = "pipelines-projects" ]]; then
            echo "ℹ️ El PR proviene de un repositorio excluido ('$PR_TARGET_REPO_NAME'). Se omite validación."
            exit 0
          fi

          echo "🔀 Pull Request: ${PR_LINK}"
          echo "🗃️ Repositorio: ${PR_TARGET_REPO_NAME}"

          matches_pattern() {
            local branch="$1"
            local pattern="$2"
            case "$branch" in
              $pattern) return 0 ;;
              *) return 1 ;;
            esac
          }
          
          validation_rules_json='${{ convertToJson(parameters.validationRules) }}'
          
          is_valid=false
          rule_index=0

          mapfile -t rules_array < <(echo "$validation_rules_json" | jq -c '.[]')

          for rule in "${rules_array[@]}"; do
            rule_index=$((rule_index + 1))
            
            target_pattern=$(echo "$rule" | jq -r '.targetBranch')
            
            IFS=$'\n' read -d '' -r -a source_patterns < <(echo "$rule" | jq -r '.sourceBranches[]')
            
            # Verificar si la rama destino coincide con el patron de la regla
            if matches_pattern "$target_branch" "$target_pattern"; then
              for source_pattern in "${source_patterns[@]}"; do
                if matches_pattern "$source_branch" "$source_pattern"; then
                  is_valid=true
                  echo "📨 PR valido: Origen '$source_branch' y destino '$target_branch' cumplen con la regla $rule_index."
                  break 2 # Salir de ambos bucles (del for y del for principal)
                fi
              done
            fi
            if [ "$is_valid" = true ]; then
              break
            fi
          done
          
          if [ "$is_valid" = true ]; then
            echo "✅ Validacion Politica Exitosa."
            exit 0
          else
            echo "⛔ Error: La combinacion de rama de origen '$source_branch' y rama destino '$target_branch'"
            echo "🚫 No esta permitida segun las reglas de la 🛂 politica definida."
            exit 1
          fi
        displayName: "🔎 Revision Politica de 🌵Ramas para Pull Request"
